version: 2
updates:
- package-ecosystem: composer
  directory: /
  schedule:
    interval: weekly
  assignees:
  - jrbasso
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  assignees:
  - jrbasso
  open-pull-requests-limit: 10
